version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: farmacia_bd
    environment:
      MYSQL_ROOT_PASSWORD: 9_NhBgXr14@2
      MYSQL_DATABASE: senac_api
    volumes:
      - volume_senac_api:/var/lib/mysql
    ports:
      - "3307:3306"

  farmacia:
    image: farmacia
    container_name: farmacia_container
    environment:
      MYSQL_HOST: farmacia_bd
      MYSQL_DATABASE: senac_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  volume_senac_api:
    external: true
